### ISSUE TITLE
Sub deps failure

### ISSUE THREAD

**Issue by mylesmegyesi** [kumarshantanu/lein-sub#2]
I have two sub projects in a root repo. When I run "lein sub deps" I get the following error.

lein sub deps
Reading project from model
Copying 2 files to /Users/mylesmegyesi/Development/metis/model/lib
Copying 4 files to /Users/mylesmegyesi/Development/metis/model/lib/dev
Reading project from validator
Copying 1 file to /Users/mylesmegyesi/Development/metis/validator/lib
Copying 4 files to /Users/mylesmegyesi/Development/metis/validator/lib/dev
Exception in thread "main" java.lang.ClassCastException: org.apache.tools.ant.types.FileSet cannot be cast to java.lang.Number (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:482)
    at clojure.lang.Var.invoke(Var.java:381)
    at clojure.lang.AFn.applyToHelper(AFn.java:178)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: org.apache.tools.ant.types.FileSet cannot be cast to java.lang.Number
    at leiningen.core$exit.invoke(core.clj:178)
    at leiningen.sub$sub.doInvoke(sub.clj:28)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.Var.invoke(Var.java:369)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$apply_task.invoke(core.clj:259)
    at leiningen.core$_main.doInvoke(core.clj:325)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$_main.invoke(core.clj:328)
    at user$eval42.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    ... 11 more

**Comment by kumarshantanu** [comment]
I pushed the fix to master – can you verify?

**Comment by mylesmegyesi** [comment]
Yep, it works now. Thanks!

**Comment by kumarshantanu** [comment]
Cool, I pushed v0.1.2 to Clojars.
